### PR TITLE
no_std support for formatting

### LINKED ISSUE #1: U*::max() function
to get "0xfffff...ffff"

### LINKED ISSUE #31: `std::fmt::Display` not implemented
Even with the sample code provided at README.md.

It's getting the following error:

```
`bigint::U256` cannot be formatted with the default formatter; try using `:?` instead if you are using a format string
   |
   = help: the trait `std::fmt::Display` is not implemented for `bigint::U256`
   = note: required by `std::fmt::Display::fmt`
```

### PR DESCRIPTION
**Pull request by Pzixel**
Includes parsing fixes as well.

Fixes #31 
Fixes #1

### CODE REVIEW

**Comment by Pzixel** [comment]
Btw tests doesn't pass in `debug` mode. It seems that you abuse fact that compiler doesn't check for overflow in release. How could I change behvior to make it work? We either must write tests without overflow or make it wrapping explicitely.

File: src/uint.rs [hunk 1]
```diff
@@ -2148,18 +2142,18 @@ mod tests {
 
 	#[test]
 	fn leading_zeros() {
-		assert_eq!(U256::from("000000000000000000000001adbdd6bd6ff027485484b97f8a6a4c7129756dd1").leading_zeros(), 95);
-		assert_eq!(U256::from("f00000000000000000000001adbdd6bd6ff027485484b97f8a6a4c7129756dd1").leading_zeros(), 0);
-		assert_eq!(U256::from("0000000000000000000000000000000000000000000000000000000000000001").leading_zeros(), 255);
-		assert_eq!(U256::from("0000000000000000000000000000000000000000000000000000000000000000").leading_zeros(), 256);
+		assert_eq!("000000000000000000000001adbdd6bd6ff027485484b97f8a6a4c7129756dd1".parse::<U256>().unwrap().leading_zeros(), 95);
```
Comment (debris) [inline src/uint.rs]: why would you change this? imo it's less readable

File: src/uint.rs [hunk 2]
```diff
@@ -955,13 +956,6 @@ macro_rules! construct_uint {
 				Ok(())
 			}
 		}
-
-		#[cfg(feature="std")]
-		impl From<&'static str> for $name {
```
Comment (debris) [inline src/uint.rs]: there is no reason to remove this

File: src/uint.rs [hunk 3]
```diff
@@ -910,34 +910,35 @@ macro_rules! construct_uint {
...
 				while !current.is_zero() {
-					s = format!("{}{}", (current % ten).low_u32(), s);
+					let digit = (current % ten).low_u32() as u8;
+					buf[i] = digit + b'0';
 					current = current / ten;
+					i -= 1;
 				}
 
-				write!(f, "{}", s)
+				let s = unsafe {::core::str::from_utf8_unchecked(&buf[i..])};
```
Comment (debris) [inline src/uint.rs]: unjustified `unsafe`

File: src/uint.rs [hunk 4]
```diff
@@ -430,7 +430,7 @@ macro_rules! construct_uint {
 				use core::cmp;
 				use rustc_hex::ToHex;;
 
-				if self.is_zero() { return "0".to_owned(); } // special case.
+				if self.is_zero() { return "0".to_owned(); } // construct_uintspecial case.
```
Comment (debris) [inline src/uint.rs]: it should be reverted or there should be a space between uint and special

**Review by debris — CHANGES_REQUESTED** [review]
> It seems that you abuse fact that compiler doesn't check for overflow in release

I don't understand this. So why they suddenly started failing for your branch and they work on master?

File: src/uint.rs (hunk 1 above)
Comment (Pzixel) [reply src/uint.rs]: Because `into` shouldn't panic. Current implementation cannot convert any string into U256. This is what `parse` is for. See comment below.

File: src/uint.rs (hunk 2 above)
Comment (Pzixel) [reply src/uint.rs]: If you cannot convert into type without panic then you shoulnd't implement `From`. 

https://doc.rust-lang.org/std/convert/trait.From.html

> Note: this trait **must not fail.**

File: src/uint.rs (hunk 3 above)
Comment (Pzixel) [reply src/uint.rs]: String of numbers is guaranteed to be a valid UTF8 string. I can leave a comment though.

File: src/uint.rs (hunk 4 above)
Comment (Pzixel) [reply src/uint.rs]: this will be reverted. Just a typo.

**Comment by Pzixel** [comment]
> I don't understand this. So why they suddenly started failing for your branch and they work on master?

~Because, if you check your `travis` file you see that all rests are executed in `release` mode. I don't think it's just ad coincendence~ I found my mistake. Sorry about that.

File: src/uint.rs (hunk 2 above)
Comment (debris) [reply src/uint.rs]: It's a convenience wrapper used only in tests (that's why it requires `'static` lifetime). We can argue here whether it's a good practice or not, but I won't accept this change cause it is used thousands of times in tests utilizing this library.

Comment (Pzixel) [reply src/uint.rs]: Ok, then it could be hidden under `#cfg[test]`? Or it's better to provide some helper trait, if you want to save 6 chars.

Comment (NikVolf) [reply src/uint.rs]: panic is not fail, it's panic (unlike typed Result<T, E> which is fail)

`[cfg(test)]` does not propagate through dependencies, and those tests mentioned are not inside this repo exclusively

and anyway, @Pzixel , how is this related to the pr topic?

Comment (Pzixel) [reply src/uint.rs]: > panic is not fail, it's panic (unlike typed Result<T, E> which is fail)

I'm pretty sure that this quote says conversion must always succeed. If you disagree, what do you think they added this note in the documentation and what does it mean? I'd really like ot make my code better, and such a basic concept worth discussing it.

> how is this related to the pr topic?

I was looking at all things with `std` attribute to deretmine if they could work in no-std environment. And then I realised that this method couldn't work anywhere. 

I probably should create another PR for it, but I strongly think that it should be done. I understand that in may require changes in depended crates, but it's really goes against rust guidelines (as I understand the docs).

Comment (mkpankov) [reply src/uint.rs]: @debris @NikVolf guys, if you need a convenience wrapper used only in tests, you can make any wrapper you'd like, just call it `parse_unwrap` or anything else, not an ecosystem-wide method with defined semantics.
There's nothing preventing a user of your library from calling `.into()` that would unexpectedly fail.

Comment (NikVolf) [reply src/uint.rs]: @mkpankov not unexpectedly, because it will fail always or not fail always (since there is no dynamic behaviour, input is static)

**Comment by Pzixel** [comment]
Now also fixes #1 (MAX was useful to test against).

**Comment by NikVolf** [comment]
looks good enough now to me, @debris ?

**Comment by NikVolf** [comment]
isn't it a bit outdated for the nightly though?

**Comment by Pzixel** [comment]
All tests pass on 2018-08-01

**Review by debris — APPROVED** [review]

**Comment by debris** [comment]
> isn't it a bit outdated for the nightly though?

What do you mean?
